# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:I4lG59eMH7hcNsLd57NpabcScmQE1kACNVfFtl+HneBfze05rjeHTU7FbcA/qRUoO694ex0R7vutmWpIH6BgBciKwC5ipTVWfgmsexOlMdglxFpXN4HIAN3ET2Xi0dYqcRxR6zHZ7dGUT7WF/1NdbXL+XxjRDT+4yUJgH5/6cL0QDvDbkl2EfKA63bliKpe0Uj1B4NZSEZ2QWA4J5wJXqZ9z8JDNNZAmHO7J3uQ+jA==,iv:3iBUl8b4KUuCduH3mgz3UdHdFQJurxBCHEVt9IrUyGI=,tag:39kT9GJ2yvZJq1eoa424UA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xaaq7rrt8v93hjseuka8c3t0l2zq5cz5zkz2dzr56d2f9ypp2pvqw9t3mg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdEJmQ05POElCd0ROdG54
        cFNKenI1WWRMUmxoRk1VVVRnamVpWVFQVEdBCllxNkxEQmRWdkJHQnF0MGRqdTZ6
        N3MwTmxXR1VXeUo2MFVvazdhSmQwY2sKLS0tIFlqVnkwZytPdXVxTU4wWG4rSGRs
        M1ZLSCtaZDVCTXUyc2NEYVVHbUNpc28Kz9NCRFAH7P0ohXjbaMG9iBLmNYzrO+Vh
        AzAq7q15ucfYp+lrlxNCcn85D4yqaPRCIWxGd6cZP8HWDIeZvk5OYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T02:08:47Z"
  mac: ENC[AES256_GCM,data:jVTDQRzDUPeOFnJBOOKY6rPLoR6N7R+oTjge8PeHgmU6XzqG7P11Od4aImU09Nc1uWzCPgloDjmTtTIs9iX6dp4Hpv3qg63QaZsfibjBQQ4YnaKeLC6cJ/xYo1s2Fy1cK7FRc5pEgc51tCWEszLzLAOHw30nf1Ngn03m2Lem/uk=,iv:VVEAMssYpfgkJccwcJxbf6hbtr58vpB4Gu6pP42fT5g=,tag:2xfiiZ+hZV+94Aim1Or9tA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
