# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:a8XueoRD94dW8x4zyCq87WtnFFG7XFApr1N2qKn/O5i7pq40H9bYBg==,iv:LsR47Hatv5kc9DTqToURiAce+k6PWAkrFrYw7QUhBe0=,tag:9iz+gBBYlgwKWsKMb9MP+g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xaaq7rrt8v93hjseuka8c3t0l2zq5cz5zkz2dzr56d2f9ypp2pvqw9t3mg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT1pVdWoyWW92aFlPRWdP
        NGxMOFJldDNIU25mNnBaaUNRTlBLdW9LM253CitzUUtLb012bUU2eXRoWmpyVVNN
        TGFvTUFzRnJTbmZlU2k5Q01heGhNSmsKLS0tIGhjRVdDTVpRWlJYQkpPQjdWSnMz
        NjFFRTIwTk12OVVNSjlSS2NTTHpuck0Kr7sMl4SW/SwzHDop9FkBZBFzAh7O9BBi
        PCGinEIGwcG81+CxT28onfKjWTBEz53t0kw6Lt8jmrt2SCjEJOR7cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T02:08:47Z"
  mac: ENC[AES256_GCM,data:OEQAHEWcyzrQ2tLT6qIkBgsu6FLmZ30FJNwyEcfHk/3iqX4IxJh+pN6DgTgF4gzJxNNhjz4sC+bsnMsxhSSYXebfciVUbp9v7E8PH/Gm4EANnAnBoiy0n3c3Cz+PmVXH1AtOkEyplCNIdf+9k+ikXku+Y8u4qmZSy9Ycew3Y7iY=,iv:KfoCThaRs/3PMwR26GhH75odMecRiR//z4aRkGug1OY=,tag:tll16r1j2W6mMCJXH7QkeA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
