# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:RilQFZ9wj0FfVj8C2ZhM2iuzFeyeTdxK9tAZpOKkghw=,iv:scsh+30f0AjtNO0Md+/uTeUGC4EP6/nWqcvf0CAYZeA=,tag:6zerul/KddlA4ImMDz7Jdw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xaaq7rrt8v93hjseuka8c3t0l2zq5cz5zkz2dzr56d2f9ypp2pvqw9t3mg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ3VlRHNGQjRmOElPeDh4
        ekhMaWVqQmtwL1cxOUxscWRrN3ZxMXZURUNjCjQyZWxHMk1GQlZqamNacU5TMDJh
        RU9rN2RjajdMOWF0c2FJZ0NrYS9pUWsKLS0tIDk0Y0JJNThiT05WZWo5dHFDTEZa
        VEd4aEVvVFR5UE00bzBYNEF4Qk1pMjAKsnyLZcLPQiqZFIMOZBpZZPo7dhs3DfKT
        tyn3aQEjymCli3mDGWdFbZt6RT49qWmf6H2BFptuSTEMojt0YElN4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T02:08:47Z"
  mac: ENC[AES256_GCM,data:tnY0gHC6YuGBMVKQkwcnbVxykSVC/FST8Rhi2MH1T7FbfwDZc577vHSu5Pj3T3Px5fJFlFFZoV0GWoPhkqVRK/KOoPCZPHt6ZtraA5sjIqNVYo4N9zY6PvqsHwT5+agW5BXsgRoF3+OKR2ezB3XcF2UOzmBOElD9t/lArMGWDqg=,iv:bgpVSaM9fKNKEVm3dW4yDlkbwAPB18LU4TAeGomlGig=,tag:0m9zjvAfrOc2FggjvIYzLg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
