apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OZYXBtfEHTQv5NEf0Q==,iv:Oz3FJJfZ7xgR0OEzL6jhjkkv4SSoupfVXCWE3Dwmwq8=,tag:MMxRnSTufxRIliAwqM28pg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xaaq7rrt8v93hjseuka8c3t0l2zq5cz5zkz2dzr56d2f9ypp2pvqw9t3mg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYmN6ZHMzQ0NoYUp1YWdV
        SWgwV2NIdVpUZStYOGd1UXE0akt1c09IWGxRCnNDaXYyM3Z6RDJ3UVByUFZQYVBn
        WUxVL0VSWVpyWGExQVg3V1hYK1NWYjgKLS0tIGVTS0RQdDkwV2FLTnRwRUFubHFC
        RTYrdkhHQjkvWmtOT2hjTG1KbVlGUXcKApU5vgGFFvKdCBBDdRFHGHqfTGdW0v7I
        4x2FZX7Ljyz46X8fzTvfa1iCxq1kJMC57hanWMWD4A2R4I425cDfhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T02:08:47Z"
  mac: ENC[AES256_GCM,data:05p82QxiuSt41QZlD7uzNDNeQEYa06CQhGwjkUpgCFo/dj/ARrJFhtXld90NONb/seAUnFcPjFiWC2sGkhO0i2K82vJSjyFGuYlm0Guwk8yy/jOH8fAYyEil9tabielryVUDtfZkJ/ICvwSZOm+NAMY08uscEpEIGYBBOpQFHpM=,iv:KYCX0kvcBdWXerPXzwnkfP44yI3LA1XUOGWf77NXRdg=,tag:ErVTn7UCCqpyNsHusur1jg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
