# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:HZ4hzGzMcKOwo8bJLwzObnB6XW4LCZFniuEoM0SN8O5VbZsxdGhjDA==,iv:J/bVtH2NIis7FrqjcwceB/ELX0Stb+RrcTPIsgtNLfc=,tag:lX+Z4RAo/ijFHDS9XhkG8g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xaaq7rrt8v93hjseuka8c3t0l2zq5cz5zkz2dzr56d2f9ypp2pvqw9t3mg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVGV2N2luZzNtOVNDUmZ5
        TnJydkkxSy9tUjBWU1RSUjZoMHZyb3hlbEV3CjUxNkNOczlhbUt2d0Q3aEU5R29T
        elNLWGZHcjRvQXo4U0xZaHIzeU9VSzQKLS0tIGo3YmhVVlBiUDhGd01namp3VkUv
        QUU2WjJ6K0daSlZmU3BqOEpIWVBhWW8K7/CtvmI9kGLaOZhcPGEMlyDENadA/qMr
        tVpTwzfBYZ5qohtW8wZWgEdB5MJzjfFhO+iSke1V3DkHVLztAKZ+Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T02:08:47Z"
  mac: ENC[AES256_GCM,data:UfgmNrCBkZDsGeRbVKOmvkv7qRjQrKKQHSyMILMopVYbBjOTD0IhA7F5InRqvX/fPEnmMBjkhxylTPgiEDOG9jJGql9MIgtrlHHaV8C7JgXGRWHPaVkAUFQSuXGdwc3j8q156mhS+uexyS824i1wIVttcQ7LkqrwnV1T04U5/FQ=,iv:xSsePy+esI3YZHUVftZ9ngHx5pq+w6M2iP9jvQCLlEU=,tag:OTmz/uMgyg9l4qIfCX3olQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
